// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MinnStateDMV.Models
{
    public partial class Dmvpersonnel
    {
        public Dmvpersonnel()
        {
            Vehicles = new HashSet<Vehicle>();
        }

        public int Dmvid { get; set; }
        public string DmvfirstName { get; set; }
        public string DmvlastName { get; set; }
        public string Dmvemail { get; set; }
        public DateTime? DmvbirthDate { get; set; }
        public DateTime? DmvhiredOn { get; set; }
        public string Dmvstreet { get; set; }
        public string Dmvcity { get; set; }
        public string Dmvstate { get; set; }
        public int? Dmvzip { get; set; }

        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}