// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MinnStateDMV.Models
{
    public partial class Infraction
    {
        public int InfractionsId { get; set; }
        public int? LawId { get; set; }
        public int? VehicleId { get; set; }
        public string InfractionType { get; set; }
        public decimal? InfractionAmount { get; set; }
        public string DriverFirstName { get; set; }
        public int? DriverSsn { get; set; }
        public string DriverPlateNumber { get; set; }

        public virtual Driver Driver { get; set; }
        public virtual LawPersonnel Law { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}