// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MinnStateDMV.Models
{
    public partial class LawPersonnel
    {
        public LawPersonnel()
        {
            Infractions = new HashSet<Infraction>();
        }

        public int LawId { get; set; }
        public string LawFirstName { get; set; }
        public string LastLastName { get; set; }
        public string LawEmail { get; set; }
        public DateTime? LawBirthDate { get; set; }
        public DateTime? LawHiredOn { get; set; }
        public string LawStreet { get; set; }
        public string LawCity { get; set; }
        public string LawState { get; set; }
        public int? LawZip { get; set; }

        public virtual ICollection<Infraction> Infractions { get; set; }
    }
}