// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MinnStateDMV.Models
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            Infractions = new HashSet<Infraction>();
        }

        public int VehicleId { get; set; }
        public int? Dmvid { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleColor { get; set; }
        public string DriverFirstName { get; set; }
        public int? DriverSsn { get; set; }
        public string DriverPlateNumber { get; set; }
        public string Insurance { get; set; }

        public virtual Dmvpersonnel Dmv { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual ICollection<Infraction> Infractions { get; set; }
    }
}