// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using MinnStateDMV.Models;

#nullable disable

namespace MinnStateDMV.Data
{
    public partial class MinnstatedmvContext : DbContext
    {
        public MinnstatedmvContext()
        {
        }

        public MinnstatedmvContext(DbContextOptions<MinnstatedmvContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Dmvpersonnel> Dmvpersonnel { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Infraction> Infractions { get; set; }
        public virtual DbSet<LawPersonnel> LawPersonnel { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Dmvpersonnel>(entity =>
            {
                entity.HasKey(e => e.Dmvid);

                entity.ToTable("DMVPersonnel");

                entity.Property(e => e.Dmvid)
                    .ValueGeneratedNever()
                    .HasColumnName("DMVID");

                entity.Property(e => e.DmvbirthDate)
                    .HasColumnType("date")
                    .HasColumnName("DMVBirthDate");

                entity.Property(e => e.Dmvcity)
                    .HasMaxLength(50)
                    .HasColumnName("DMVCity");

                entity.Property(e => e.Dmvemail)
                    .HasMaxLength(50)
                    .HasColumnName("DMVEmail");

                entity.Property(e => e.DmvfirstName)
                    .HasMaxLength(50)
                    .HasColumnName("DMVFirstName");

                entity.Property(e => e.DmvhiredOn)
                    .HasColumnType("date")
                    .HasColumnName("DMVHiredOn");

                entity.Property(e => e.DmvlastName)
                    .HasMaxLength(50)
                    .HasColumnName("DMVLastName");

                entity.Property(e => e.Dmvstate)
                    .HasMaxLength(50)
                    .HasColumnName("DMVState");

                entity.Property(e => e.Dmvstreet)
                    .HasMaxLength(50)
                    .HasColumnName("DMVStreet");

                entity.Property(e => e.Dmvzip).HasColumnName("DMVZip");
            });

            modelBuilder.Entity<Driver>(entity =>
            {
                entity.HasKey(e => new { e.DriverFirstName, e.DriverSsn, e.DriverPlateNumber });

                entity.Property(e => e.DriverFirstName).HasMaxLength(50);

                entity.Property(e => e.DriverSsn).HasColumnName("DriverSSN");

                entity.Property(e => e.DriverPlateNumber).HasMaxLength(50);

                entity.Property(e => e.DriverBirthDate).HasColumnType("date");

                entity.Property(e => e.DriverCity).HasMaxLength(50);

                entity.Property(e => e.DriverLastName).HasMaxLength(50);

                entity.Property(e => e.DriverState).HasMaxLength(50);

                entity.Property(e => e.DriverStreet).HasMaxLength(50);
            });

            modelBuilder.Entity<Infraction>(entity =>
            {
                entity.HasKey(e => e.InfractionsId);

                entity.Property(e => e.InfractionsId)
                    .ValueGeneratedNever()
                    .HasColumnName("InfractionsID");

                entity.Property(e => e.DriverFirstName).HasMaxLength(50);

                entity.Property(e => e.DriverPlateNumber).HasMaxLength(50);

                entity.Property(e => e.DriverSsn).HasColumnName("DriverSSN");

                entity.Property(e => e.InfractionAmount).HasColumnType("money");

                entity.Property(e => e.InfractionType).HasMaxLength(50);

                entity.Property(e => e.LawId).HasColumnName("LawID");

                entity.Property(e => e.VehicleId).HasColumnName("VehicleID");

                entity.HasOne(d => d.Law)
                    .WithMany(p => p.Infractions)
                    .HasForeignKey(d => d.LawId)
                    .HasConstraintName("FK_Infractions_LawPersonnel");

                entity.HasOne(d => d.Vehicle)
                    .WithMany(p => p.Infractions)
                    .HasForeignKey(d => d.VehicleId)
                    .HasConstraintName("FK_Infractions_Vehicles");

                entity.HasOne(d => d.Driver)
                    .WithMany(p => p.Infractions)
                    .HasForeignKey(d => new { d.DriverFirstName, d.DriverSsn, d.DriverPlateNumber })
                    .HasConstraintName("FK_Infractions_Drivers");
            });

            modelBuilder.Entity<LawPersonnel>(entity =>
            {
                entity.HasKey(e => e.LawId);

                entity.Property(e => e.LawId)
                    .ValueGeneratedNever()
                    .HasColumnName("LawID");

                entity.Property(e => e.LastLastName).HasMaxLength(50);

                entity.Property(e => e.LawBirthDate).HasColumnType("date");

                entity.Property(e => e.LawCity).HasMaxLength(50);

                entity.Property(e => e.LawEmail).HasMaxLength(50);

                entity.Property(e => e.LawFirstName).HasMaxLength(50);

                entity.Property(e => e.LawHiredOn).HasColumnType("date");

                entity.Property(e => e.LawState).HasMaxLength(50);

                entity.Property(e => e.LawStreet).HasMaxLength(50);
            });

            modelBuilder.Entity<Vehicle>(entity =>
            {
                entity.Property(e => e.VehicleId)
                    .ValueGeneratedNever()
                    .HasColumnName("VehicleID");

                entity.Property(e => e.Dmvid).HasColumnName("DMVID");

                entity.Property(e => e.DriverFirstName).HasMaxLength(50);

                entity.Property(e => e.DriverPlateNumber).HasMaxLength(50);

                entity.Property(e => e.DriverSsn).HasColumnName("DriverSSN");

                entity.Property(e => e.Insurance).HasMaxLength(50);

                entity.Property(e => e.VehicleColor).HasMaxLength(50);

                entity.Property(e => e.VehicleModel).HasMaxLength(50);

                entity.HasOne(d => d.Dmv)
                    .WithMany(p => p.Vehicles)
                    .HasForeignKey(d => d.Dmvid)
                    .HasConstraintName("FK_Vehicles_DMVPersonnel");

                entity.HasOne(d => d.Driver)
                    .WithMany(p => p.Vehicles)
                    .HasForeignKey(d => new { d.DriverFirstName, d.DriverSsn, d.DriverPlateNumber })
                    .HasConstraintName("FK_Vehicles_Drivers");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}